apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
data:
  secretuser: {{ required ".Values.crichterSimpleWebserver.secretuser variable is missing" $.Values.crichterSimpleWebserver.secretuser | b64enc | quote }}